DROP TABLE IF EXISTS ADN;

CREATE TABLE ADN (
  ID INT NOT NULL AUTO_INCREMENT,
  ADN_STRING VARCHAR(250) NOT NULL,
  TYPE_ADN INT NOT NULL
  PRIMARY KEY (`Id`));

DROP TABLE IF EXISTS Type_Adn;

CREATE TABLE TYPE_ADN (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id`));